
ALTER TYPE log_type ADD VALUE IF NOT EXISTS 'WELFARE_CHECK';
ALTER TYPE log_type ADD VALUE IF NOT EXISTS 'CCTV_CHECK';
ALTER TYPE log_type ADD VALUE IF NOT EXISTS 'MANAGEMENT_VISIT';
ALTER TYPE log_type ADD VALUE IF NOT EXISTS 'VISITOR';
ALTER TYPE log_type ADD VALUE IF NOT EXISTS 'ACCESS_CONTROL';
ALTER TYPE log_type ADD VALUE IF NOT EXISTS 'MAINTENANCE';
ALTER TYPE log_type ADD VALUE IF NOT EXISTS 'HANDOVER';
ALTER TYPE log_type ADD VALUE IF NOT EXISTS 'ALARM';
ALTER TYPE log_type ADD VALUE IF NOT EXISTS 'FIRE_ALARM';
ALTER TYPE log_type ADD VALUE IF NOT EXISTS 'EMERGENCY';

